In [2]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import random

In [3]:
train_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_train_small.csv")

In [4]:
train_df

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
19994  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19996  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19997  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19998  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   

       0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [5]:
num_col=train_df.shape[1]

In [6]:
num_row=train_df.shape[0]

In [7]:
feat=train_df.drop(["6"],axis=1)

In [8]:
list1=np.ones(num_row, dtype = int)

In [9]:
feat.insert(loc=0, column='A', value=list1)

In [10]:
feat

A  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
19994  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19996  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19997  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19998  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

       0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [11]:
x_train1=feat.to_numpy()

In [12]:
x_train=x_train1.astype('float64') #19999 * 785

In [13]:
label=train_df["6"]

In [14]:
label=label.to_numpy()

In [15]:
label

array([5, 7, 9, ..., 2, 9, 5], dtype=int64)

In [16]:
y_train=np.reshape(label,(1,num_row))

In [19]:
class training:
    def __init__(self,x,y,no_of_iters,learn_rate,a,b):
        self.xset=x
        self.yset=y
        self.iters=no_of_iters
        self.learn=learn_rate
        self.numrow=a
        self.numcol=b
    def train(self): #a-num_row,b-num_col
        theta=np.zeros((1,self.numcol),dtype=float)
        self.predi=np.dot(theta,np.transpose(self.xset))
        for m in range(0,self.iters):
            D=np.dot((self.predi-self.yset),self.xset)# 1*785
            theta1=theta
            theta=theta-((self.learn/self.numrow)*D)
            theta[0][0]=theta1[0][0]-((self.learn/self.numrow)*np.sum(self.predi-self.yset))
            self.predi=np.dot(theta,np.transpose(self.xset))
        cost=(1/2*self.numrow)*np.sum(np.square(self.predi-self.yset))
        return(theta)
    
    
    

In [18]:
training(x_train,y_train,3000,0.0000008,num_row,num_col).train()

(array([[ 4.10043063e-04,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00, -1.65506837e-06, -3.57494769e-05,
         -3.57494769e-05, -1.48956154e-06,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  9.87194502e-05,
          1.72775211e-04,  2.12700377e-04,  2.06681159e-04,
          1.99696532e-04,  8.81038279e-05,  2.69459626e-04,
          1.61206328e-04,  2.59666848e-04,  3.62278271e-04,
          2.96702795e-04,  2.05945145e-04,  2.62537182e-04,
          1.20851308e-04,  9.06146284e-0

Testing

In [20]:
theta=training(x_train,y_train,3000,0.0000008,num_row,num_col).train()

In [21]:
test_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_test.csv")

In [48]:
test_df

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [36]:
num_row1=test_df.shape[0]

In [37]:
num_col1=test_df.shape[1]

In [38]:
feat1=test_df.drop(["7"],axis=1)

In [39]:
list2=np.ones(num_row1, dtype = int)

In [40]:
feat1.insert(loc=0, column='A', value=list2)

In [42]:
x_test1=feat1.to_numpy()

In [43]:
x_test=x_test1.astype('float64')

In [52]:
label1=test_df["7"]

In [53]:
label1=label1.to_numpy()

In [57]:
y_test=np.reshape((label1),(1,num_row1))

In [58]:
y_test

array([[2, 1, 0, ..., 4, 5, 6]], dtype=int64)

In [46]:
predicted_output=np.dot(theta,(np.transpose(x_test)))

In [47]:
predicted_output

array([[2.02466935, 0.8368569 , 1.34269175, ..., 8.65626761, 5.48791036,
        6.79932385]])

In [60]:
cost1=(1/2*num_row1)*np.sum(np.square(predicted_output-y_test))

In [61]:
cost1

178984392.98158398

In [73]:
'''Write the testing example for which you want output'''
n=int(input())
print("The predicted output is {}".format(predicted_output[0][n]))
print("The real value is {}".format(y_test[0][n]))


 378


The predicted output is 4.047612525396908
The real value is 4


In [74]:
'''Write the testing example for which you want output'''
n=int(input())
print("The predicted output is {}".format(predicted_output[0][n]))
print("The real value is {}".format(y_test[0][n]))

 2345


The predicted output is 4.951812204716319
The real value is 5


In [75]:
'''Write the testing example for which you want output'''
n=int(input())
print("The predicted output is {}".format(predicted_output[0][n]))
print("The real value is {}".format(y_test[0][n]))

 5678


The predicted output is 1.0298556377787873
The real value is 1
