IMPORTING MODULES

In [18]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import random
import collections
compare = lambda x, y: collections.Counter(x) == collections.Counter(y)


IMPORTING DATASET

In [19]:
train_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_train_small.csv")
test_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_test.csv")


In [20]:
train_df.head()

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [21]:
train_df["0.56"]

0        0
1        0
2        0
3        0
4        0
        ..
19994    0
19995    0
19996    0
19997    0
19998    0
Name: 0.56, Length: 19999, dtype: int64

In [22]:
df_new = train_df.rename(columns={'6': 'Label'})

In [23]:
df_new.head()

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [24]:
df_new

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  \
0          5  0    0    0    0    0    0    0    0    0  ...      0      0   
1          7  0    0    0    0    0    0    0    0    0  ...      0      0   
2          9  0    0    0    0    0    0    0    0    0  ...      0      0   
3          5  0    0    0    0    0    0    0    0    0  ...      0      0   
4          2  0    0    0    0    0    0    0    0    0  ...      0      0   
...      ... ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
19994      0  0    0    0    0    0    0    0    0    0  ...      0      0   
19995      1  0    0    0    0    0    0    0    0    0  ...      0      0   
19996      2  0    0    0    0    0    0    0    0    0  ...      0      0   
19997      9  0    0    0    0    0    0    0    0    0  ...      0      0   
19998      5  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.583  0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [25]:
len(df_new.index)

19999

In [26]:
matx=df_new.drop(["Label"], axis=1)

Adding one more column with entries 1

In [27]:
list1=[]
for i in range (0,19999):
    list1.append(1)

Defining a function for matrix multiplication

In [28]:
def matmul(a,b):
    p = len(a)    #rows
    #q = len(a[0]) #columns
    #r = len(b)    
    s = len(b[0])
    #d=np.zeros((3,4),dtype=int)
    d=np.zeros((p,s),dtype=float)
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                d[i][j] += a[i][k] * b[k][j]
    return(d[0][0])

    
    

Initializing the weights

In [29]:
theta=np.zeros((1,785),dtype=float)

In [30]:
theta

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [31]:
for i in range(0,785):
    theta[0][i]=0

In [32]:
theta

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [33]:
matx

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.581  0.582  \
0      0    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      0    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      0    0    0    0    0    0    0    0    0    0  ...      0      0   
...   ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
19994  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19995  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19996  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19997  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19998  0    0    0    0    0    0    0    0    0    0  ...      0      0   

       0.583  0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0      0  

[19999 rows x 784 columns]

In [34]:
matx.insert(loc=0, column='A', value=list1)

Dataframe with all the variables

In [35]:
matx

A  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
19994  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19996  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19997  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19998  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

       0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [36]:
arrx = matx.to_numpy()
arrx = arrx.astype('float64') 

In [37]:
arrx

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

Creating list of features

In [38]:
maty=df_new["Label"]
arry=maty.to_numpy()
arry = arry.astype('float64') 

In [39]:
arry

array([5., 7., 9., ..., 2., 9., 5.])

Defining derivative function

In [40]:
def summation(a,b,c,j):
    for i in range(0,19999):
        X=0
        X=X+((a[i]-b[i])*c[i][j])
    return(X)
    

Creating a function that returns list of predicted ouputs for all test cases

In [41]:
predout=np.zeros((19999),dtype=float)
for i in range(0,19999):
    entry=arrx[i]
    entry1=entry.reshape(785,1)
    predout[i]=matmul(theta,entry1)
    
    
    
    
    

In [42]:
predout

array([0., 0., 0., ..., 0., 0., 0.])

Training the data set and calculating the weights

In [43]:
def ffff(e):
    for i in range(0,19999):
        x=np.sum((predout[i]-arry[i])*arrx[i][e])
    return(x)

In [64]:
def training():
    f=0.0001
    for m in range(0,5):
        for j in range(0,785):
            theta[0][j]=theta[0][j]-((f/19999)*(ffff(j)))
        predout=np.zeros((19999),dtype=float)
        for i in range(0,19999):
            entry=arrx[i]
            entry1=entry.reshape(785,1)
            predout[i]=matmul(theta,entry1)
    return(theta,predout)
training()
    
    

(array([[7.50037502e-07, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000

Defing a cost function

In [50]:
def cost():
    pred_out=np.zeros((19999),dtype=float)
    for i in range(0,19999):
        entry=arrx[i]
        entry1=entry.reshape(785,1)
        pred_out[i]=matmul(theta,entry1)
    for k in range(0,19999):
        j=((pred_out[k]-arry[k])*(pred_out[k]-arry[k]))/(2*19999)
    return(j,pred_out)
    

Final Calculated Cost

In [71]:
cost()

(9.896047774353443e-06,
 array([2.0100345 , 1.36830392, 2.26641907, ..., 1.21445622, 1.29972574,
        5.62914396]))

In [59]:
alphas=theta

In [67]:
arry

array([5., 7., 9., ..., 2., 9., 5.])

Testing

In [100]:
test_df

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [101]:
df_new1 = test_df.rename(columns={'7': 'Label'})

In [102]:
df_new1

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  \
0         2  0    0    0    0    0    0    0    0    0  ...      0      0   
1         1  0    0    0    0    0    0    0    0    0  ...      0      0   
2         0  0    0    0    0    0    0    0    0    0  ...      0      0   
3         4  0    0    0    0    0    0    0    0    0  ...      0      0   
4         1  0    0    0    0    0    0    0    0    0  ...      0      0   
...     ... ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
9994      2  0    0    0    0    0    0    0    0    0  ...      0      0   
9995      3  0    0    0    0    0    0    0    0    0  ...      0      0   
9996      4  0    0    0    0    0    0    0    0    0  ...      0      0   
9997      5  0    0    0    0    0    0    0    0    0  ...      0      0   
9998      6  0    0    0    0    0    0    0    0    0  ...      0      0   

      0.660  0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [103]:
inpx=df_new1.drop(["Label"], axis=1)

In [104]:
list2=[]
for i in range (0,9999):
    list2.append(1)

In [105]:
inpx.insert(loc=0, column='A', value=list2)

In [106]:
inpx

A  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [107]:
inparr = inpx.to_numpy()

In [108]:
inparr

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [109]:
pred_Out=np.zeros((9999),dtype=int)
for i in range(0,9999):
    entry=inparr[i]
    entry1=entry.reshape(785,1)
    pred_Out[i]=matmul(theta,entry1)
    

In [113]:
maty1=df_new1["Label"]
arry1=maty1.to_numpy()

In [114]:
arry1

array([2, 1, 0, ..., 4, 5, 6], dtype=int64)

In [132]:
l=int(input("Enter the row for which you want output"))

Enter the row for which you want output 5000


In [134]:
print("The predicted output is {}.".format(pred_Out[l]))
print("The real output is {}.".format(arry[l]))

The predicted output is 1.
The real output is 1.0.


In [136]:
print("The predicted output is {}.".format(pred_Out[930]))
print("The real output is {}.".format(arry[930]))

The predicted output is 0.
The real output is 1.0.
