IMPORTING MODULES

In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import random
import collections
compare = lambda x, y: collections.Counter(x) == collections.Counter(y)


IMPORTING DATASET

In [2]:
train_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_train_small.csv")
test_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_test.csv")


In [3]:
train_df.head()

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [4]:
train_df["0.56"]

0        0
1        0
2        0
3        0
4        0
        ..
19994    0
19995    0
19996    0
19997    0
19998    0
Name: 0.56, Length: 19999, dtype: int64

In [5]:
df_new = train_df.rename(columns={'6': 'Label'})

In [6]:
df_new.head()

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [7]:
df_new

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  \
0          5  0    0    0    0    0    0    0    0    0  ...      0      0   
1          7  0    0    0    0    0    0    0    0    0  ...      0      0   
2          9  0    0    0    0    0    0    0    0    0  ...      0      0   
3          5  0    0    0    0    0    0    0    0    0  ...      0      0   
4          2  0    0    0    0    0    0    0    0    0  ...      0      0   
...      ... ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
19994      0  0    0    0    0    0    0    0    0    0  ...      0      0   
19995      1  0    0    0    0    0    0    0    0    0  ...      0      0   
19996      2  0    0    0    0    0    0    0    0    0  ...      0      0   
19997      9  0    0    0    0    0    0    0    0    0  ...      0      0   
19998      5  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.583  0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [8]:
len(df_new.index)

19999

In [9]:
matx=df_new.drop(["Label"], axis=1)

Adding one more column with entries 1

In [10]:
list1=[]
for i in range (0,19999):
    list1.append(1)

Defining a function for matrix multiplication

In [11]:
def matmul(a,b):
    p = len(a)    #rows
    #q = len(a[0]) #columns
    #r = len(b)    
    s = len(b[0])
    #d=np.zeros((3,4),dtype=int)
    d=np.zeros((p,s),dtype=float)
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                d[i][j] += a[i][k] * b[k][j]
    return(d[0][0])

    
    

Initializing the weights

In [12]:
theta=np.zeros((1,785),dtype=float)

In [13]:
theta

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [48]:
for i in range(0,785):
    theta[0][i]=0

In [49]:
theta

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [17]:
matx

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.581  0.582  \
0      0    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      0    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      0    0    0    0    0    0    0    0    0    0  ...      0      0   
...   ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
19994  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19995  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19996  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19997  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19998  0    0    0    0    0    0    0    0    0    0  ...      0      0   

       0.583  0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0      0  

[19999 rows x 784 columns]

In [18]:
matx.insert(loc=0, column='A', value=list1)

Dataframe with all the variables

In [19]:
matx

A  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
19994  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19996  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19997  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19998  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

       0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [20]:
arrx = matx.to_numpy()
arrx = arrx.astype('float64') 

In [21]:
arrx

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

Creating list of features

In [22]:
maty=df_new["Label"]
arry=maty.to_numpy()
arry = arry.astype('float64') 

In [23]:
arry

array([5., 7., 9., ..., 2., 9., 5.])

Defining derivative function

In [24]:
def summation(a,b,c,j):
    for i in range(0,19999):
        X=0
        X=X+((a[i]-b[i])*c[i][j])
    return(X)
    

Creating a function that returns list of predicted ouputs for all test cases

In [50]:
predout=np.zeros((19999),dtype=float)
for i in range(0,19999):
    entry=arrx[i]
    entry1=entry.reshape(785,1)
    predout[i]=matmul(theta,entry1)
    
    
    
    
    

In [29]:
predout

array([ 98309., 121117., 128471., ..., 156496., 105025., 165252.])

Training the data set and calculating the weights

In [52]:
def ffff(e):
    for i in range(0,19999):
        x=np.sum((predout[i]-arry[i])*arrx[i][e])
    return(x)

In [ ]:
def training():
    f=0.0001
    for m in range(0,50):
        for j in range(0,785):
            theta[0][j]=theta[0][j]-((f/19999)*(ffff(j)))
        predout=np.zeros((19999),dtype=float)
        for i in range(0,19999):
            entry=arrx[i]
            entry1=entry.reshape(785,1)
            predout[i]=matmul(theta,entry1)
    return(theta,predout)
training()
    
    

Defing a cost function

In [54]:
def cost():
    pred_out=np.zeros((19999),dtype=float)
    for i in range(0,19999):
        entry=arrx[i]
        entry1=entry.reshape(785,1)
        pred_out[i]=matmul(theta,entry1)
    for k in range(0,19999):
        j=((pred_out[k]-arry[k])*(pred_out[k]-arry[k]))/(2*19999)
    return(j,pred_out)
    

Final Calculated Cost

In [55]:
cost()

(0.0004800516378367588,
 array([3.3500575 , 2.28050653, 3.77736512, ..., 2.0240937 , 2.16620956,
        9.3819066 ]))

In [28]:
arry

array([5, 7, 9, ..., 2, 9, 5], dtype=int64)

predout=np.zeros((19999),dtype=int)
for i in range(0,19999):
    entry=arrx[i]
    entry1=entry.reshape(785,1)
    predout[i]=matmul(theta,entry1)

In [30]:
predout

array([ 91537, 100927, 105367, ..., 156455,  81153,  86837])

Testing

In [110]:
test_df

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [112]:
df_new1 = test_df.rename(columns={'7': 'Label'})

In [113]:
df_new1

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  \
0         2  0    0    0    0    0    0    0    0    0  ...      0      0   
1         1  0    0    0    0    0    0    0    0    0  ...      0      0   
2         0  0    0    0    0    0    0    0    0    0  ...      0      0   
3         4  0    0    0    0    0    0    0    0    0  ...      0      0   
4         1  0    0    0    0    0    0    0    0    0  ...      0      0   
...     ... ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
9994      2  0    0    0    0    0    0    0    0    0  ...      0      0   
9995      3  0    0    0    0    0    0    0    0    0  ...      0      0   
9996      4  0    0    0    0    0    0    0    0    0  ...      0      0   
9997      5  0    0    0    0    0    0    0    0    0  ...      0      0   
9998      6  0    0    0    0    0    0    0    0    0  ...      0      0   

      0.660  0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [114]:
inpx=df_new.drop(["Label"], axis=1)

In [118]:
list2=[]
for i in range (0,9999):
    list2.append(1)

In [119]:
inpx.insert(loc=0, column='A', value=list2)

In [120]:
inpx

A  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [121]:
inparr = inpx.to_numpy()

In [122]:
inparr

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [125]:
pred_Out=np.zeros((9999),dtype=int)
for i in range(0,9999):
    entry=arrx[i]
    entry1=entry.reshape(785,1)
    pred_Out[i]=matmul(theta,entry1)
    

In [123]:
maty1=df_new["Label"]
arry1=maty.to_numpy()

In [124]:
arry1

array([2, 1, 0, ..., 4, 5, 6], dtype=int64)

In [129]:
l=int(input("Enter the row for which you want output"))

Enter the row for which you want output 50


In [130]:
print("The predicted output is {}.".format(pred_Out[l]))
print("The real output is {}.".format(arry[l]))
m=((pred_Out[l]-arry[l])/arry[l])*100
print("The error is {} percent".format(m))

The predicted output is -5474478.
The real output is 3.
The error is -182482700.0 percent


In [131]:
pred_Out

array([-6137443, -4145614, -6930476, ..., -5351334, -3824892, -5810136])