IMPORTING MODULES

In [70]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import random

IMPORTING DATASET

In [71]:
train_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_train_small.csv")
test_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_test.csv")


In [72]:
train_df.head()

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [73]:
train_df["0.56"]

0        0
1        0
2        0
3        0
4        0
        ..
19994    0
19995    0
19996    0
19997    0
19998    0
Name: 0.56, Length: 19999, dtype: int64

In [74]:
df_new = train_df.rename(columns={'6': 'Label'})

In [75]:
df_new.head()

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [76]:
df_new

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  \
0          5  0    0    0    0    0    0    0    0    0  ...      0      0   
1          7  0    0    0    0    0    0    0    0    0  ...      0      0   
2          9  0    0    0    0    0    0    0    0    0  ...      0      0   
3          5  0    0    0    0    0    0    0    0    0  ...      0      0   
4          2  0    0    0    0    0    0    0    0    0  ...      0      0   
...      ... ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
19994      0  0    0    0    0    0    0    0    0    0  ...      0      0   
19995      1  0    0    0    0    0    0    0    0    0  ...      0      0   
19996      2  0    0    0    0    0    0    0    0    0  ...      0      0   
19997      9  0    0    0    0    0    0    0    0    0  ...      0      0   
19998      5  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.583  0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [77]:
len(df_new.index)

19999

In [78]:
matx=df_new.drop(["Label"], axis=1)

Adding one more column with entries 1

In [79]:
list1=[]
for i in range (0,19999):
    list1.append(1)

Defining a function for matrix multiplication

In [80]:
def matmul(a,b):
    p = len(a)    #rows
    #q = len(a[0]) #columns
    #r = len(b)    
    s = len(b[0])
    #d=np.zeros((3,4),dtype=int)
    d=np.zeros((p,s),dtype=int)
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                d[i][j] += a[i][k] * b[k][j]
    return(d[0][0])

    
    

Initializing the weights

In [81]:
theta=np.zeros((1,785),dtype=int)

In [82]:
theta

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [83]:
for i in range(0,785):
    theta[0][i]=random.randint(0,9)

In [84]:
theta

array([[7, 2, 7, 0, 2, 0, 0, 7, 5, 1, 7, 8, 3, 5, 7, 7, 9, 7, 7, 4, 5, 3,
        9, 1, 9, 3, 9, 0, 8, 4, 0, 1, 7, 0, 4, 9, 8, 7, 9, 5, 5, 8, 1, 9,
        4, 5, 7, 0, 8, 8, 1, 1, 3, 2, 6, 5, 1, 9, 8, 1, 6, 9, 7, 5, 5, 2,
        2, 6, 4, 8, 1, 0, 6, 1, 5, 0, 2, 5, 4, 8, 6, 2, 5, 2, 2, 3, 4, 9,
        4, 9, 4, 5, 4, 2, 5, 4, 5, 8, 3, 9, 3, 4, 0, 0, 8, 7, 3, 2, 0, 7,
        6, 8, 2, 9, 5, 8, 1, 0, 6, 4, 5, 7, 9, 9, 1, 8, 3, 8, 0, 8, 3, 2,
        1, 5, 1, 5, 8, 2, 3, 5, 9, 0, 7, 7, 2, 7, 7, 7, 5, 6, 4, 7, 4, 6,
        6, 9, 8, 8, 1, 8, 3, 8, 5, 9, 8, 5, 3, 6, 0, 5, 5, 0, 0, 8, 3, 9,
        9, 7, 3, 4, 1, 6, 1, 8, 4, 9, 5, 2, 9, 9, 0, 7, 9, 6, 9, 9, 9, 3,
        3, 5, 9, 2, 2, 6, 0, 3, 6, 6, 9, 5, 1, 4, 6, 5, 3, 9, 3, 1, 2, 7,
        5, 9, 0, 9, 3, 6, 0, 6, 6, 1, 7, 0, 1, 1, 4, 5, 4, 6, 2, 8, 5, 3,
        0, 2, 7, 7, 4, 6, 0, 4, 6, 8, 2, 5, 3, 5, 8, 5, 0, 5, 8, 9, 4, 1,
        9, 4, 0, 4, 7, 1, 5, 4, 3, 4, 6, 7, 9, 6, 3, 6, 2, 6, 3, 2, 8, 8,
        4, 0, 2, 5, 2, 2, 1, 3, 8, 4, 

In [85]:
matx

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.581  0.582  \
0      0    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      0    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      0    0    0    0    0    0    0    0    0    0  ...      0      0   
...   ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
19994  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19995  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19996  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19997  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19998  0    0    0    0    0    0    0    0    0    0  ...      0      0   

       0.583  0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0      0  

[19999 rows x 784 columns]

In [86]:
matx.insert(loc=0, column='A', value=list1)

Dataframe with all the variables

In [87]:
matx

A  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
19994  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19996  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19997  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19998  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

       0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [88]:
arrx = matx.to_numpy()

In [89]:
arrx

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

Creating list of features

In [90]:
maty=df_new["Label"]
arry=maty.to_numpy()

Defining derivative function

In [92]:
def summation(a,b,c,j):
    for i in range(0,19999):
        X=0
        X=X+((a[i]-b[i])*c[i][j])
    return(X)
    

Creating a function that returns list of predicted ouputs for all test cases

In [93]:
maty=df_new["Label"]
arry=maty.to_numpy()
predout=np.zeros((19999),dtype=int)
for i in range(0,19999):
    entry=arrx[i]
    entry1=entry.reshape(785,1)
    predout[i]=matmul(theta,entry1)
    
    
    
    
    

Training the data set and calculating the weights

In [103]:
def training():
    f=0.1
    i=1
    for i in range(0,20000):
        theta1=theta
        for j in range(0,785):
            theta[0][j]=theta[0][j]-((f/19999)*summation(predout,arry,arrx,j))
        if set(theta1[0]) == set(theta[0]):
            break
    return(theta)
training()
    
    

array([[   4,    2,    7,    0,    2,    0,    0,    7,    5,    1,    7,
           8,    3,    5,    7,    7,    9,    7,    7,    4,    5,    3,
           9,    1,    9,    3,    9,    0,    8,    4,    0,    1,    7,
           0,    4,    9,    8,    7,    9,    5,    5,    8,    1,    9,
           4,    5,    7,    0,    8,    8,    1,    1,    3,    2,    6,
           5,    1,    9,    8,    1,    6,    9,    7,    5,    5,    2,
           2,    6,    4,    8,    1,    0,    6,    1,    5,    0,    2,
           5,    4,    8,    6,    2,    5,    2,    2,    3,    4,    9,
           4,    9,    4,    5,    4,    2,    5,    4,    5,    8,    3,
           9,    3,    4,    0,    0,    8,    7,    3,    2,    0,    7,
           6,    8,    2,    9,    5,    8,    1,    0,    6,    4,    5,
           7,    9,    9,    1,    8,    3,    8,    0,    8,    3,    2,
           1,    5,    1,    5,    8,    2,    3,    5,    9,    0,    7,
           7,    2,    7,    7,    7, 

In [104]:
theta

array([[   4,    2,    7,    0,    2,    0,    0,    7,    5,    1,    7,
           8,    3,    5,    7,    7,    9,    7,    7,    4,    5,    3,
           9,    1,    9,    3,    9,    0,    8,    4,    0,    1,    7,
           0,    4,    9,    8,    7,    9,    5,    5,    8,    1,    9,
           4,    5,    7,    0,    8,    8,    1,    1,    3,    2,    6,
           5,    1,    9,    8,    1,    6,    9,    7,    5,    5,    2,
           2,    6,    4,    8,    1,    0,    6,    1,    5,    0,    2,
           5,    4,    8,    6,    2,    5,    2,    2,    3,    4,    9,
           4,    9,    4,    5,    4,    2,    5,    4,    5,    8,    3,
           9,    3,    4,    0,    0,    8,    7,    3,    2,    0,    7,
           6,    8,    2,    9,    5,    8,    1,    0,    6,    4,    5,
           7,    9,    9,    1,    8,    3,    8,    0,    8,    3,    2,
           1,    5,    1,    5,    8,    2,    3,    5,    9,    0,    7,
           7,    2,    7,    7,    7, 

In [ ]:
Defing a cos function

In [107]:
def cost():
    pred_out=np.zeros((19999),dtype=int)
    for i in range(0,19999):
        entry=arrx[i]
        entry1=entry.reshape(785,1)
        predout[i]=matmul(theta,entry1)
    for k in range(0,19999):
        j=((pred_out[k]-arry[k])*(pred_out[k]-arry[k]))/(2*19999)
    return(j)
    

In [108]:
cost()

0.0006250312515625781