In [65]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import random

In [66]:
train_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_train_small.csv")
test_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_test.csv")


In [67]:
train_df.head()

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [68]:
df_new = train_df.rename(columns={'6': 'Label'})

In [69]:
df_new.head()

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

df_new['Label']= df_new["Label"].replace({1:0, 2: 0, 3: 0, 4: 0, 5 : 0, 6: 0, 7: 0, 8: 0, 9: 0, 0: 1}, inplace=True)

In [70]:
df_new['Label'] = df_new['Label'].replace([0,1,2,3,4,5,6,7,8,9],[1,0,0,0,0,0,0,0,0,0])

In [71]:
df_new

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  \
0          0  0    0    0    0    0    0    0    0    0  ...      0      0   
1          0  0    0    0    0    0    0    0    0    0  ...      0      0   
2          0  0    0    0    0    0    0    0    0    0  ...      0      0   
3          0  0    0    0    0    0    0    0    0    0  ...      0      0   
4          0  0    0    0    0    0    0    0    0    0  ...      0      0   
...      ... ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
19994      1  0    0    0    0    0    0    0    0    0  ...      0      0   
19995      0  0    0    0    0    0    0    0    0    0  ...      0      0   
19996      0  0    0    0    0    0    0    0    0    0  ...      0      0   
19997      0  0    0    0    0    0    0    0    0    0  ...      0      0   
19998      0  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.583  0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [86]:
def sigmoid(z):
    return (1.0 / (1 + np.exp(-z)))

In [73]:
matx=df_new.drop(["Label"], axis=1)

In [74]:
matx

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.581  0.582  \
0      0    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      0    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      0    0    0    0    0    0    0    0    0    0  ...      0      0   
...   ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
19994  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19995  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19996  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19997  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19998  0    0    0    0    0    0    0    0    0    0  ...      0      0   

       0.583  0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0      0  

[19999 rows x 784 columns]

In [75]:
list1=[]
for i in range (0,19999):
    list1.append(1)

In [76]:
matx.insert(loc=0, column='A', value=list1)

In [77]:
matx

A  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
19994  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19996  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19997  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19998  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

       0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [78]:
arrx = matx.to_numpy()
arrx = arrx.astype('float64') 

In [79]:
arrx

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [80]:
maty=df_new["Label"]
arry=maty.to_numpy()
arry = arry.astype('float64') 

In [81]:
arry

array([0., 0., 0., ..., 0., 0., 0.])

In [82]:
theta=np.zeros((1,785),dtype=float)

In [83]:
for i in range(0,785):
    theta[0][i]=0

In [84]:
theta

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [85]:
def matmul(a,b):
    p = len(a)    #rows
    #q = len(a[0]) #columns
    #r = len(b)    
    s = len(b[0])
    #d=np.zeros((3,4),dtype=int)
    d=np.zeros((p,s),dtype=float)
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                d[i][j] += a[i][k] * b[k][j]
    return(d[0][0])


In [ ]:
predout=np.zeros((19999),dtype=float)
for i in range(0,19999):
    entry=arrx[i]
    entry1=entry.reshape(785,1)
    predout[i]=sigmoid(matmul(theta,entry1))
    

In [ ]:
def ffff(e):
    for i in range(0,19999):
        x=np.sum((predout[i]-arry[i])*arrx[i][e])
    return(x)

In [ ]:
def training():
    f=0.0001
    for m in range(0,100):
        for j in range(0,785):
            theta[0][j]=theta[0][j]-((f/19999)*(ffff(j)))
        predout=np.zeros((19999),dtype=float)
        for i in range(0,19999):
            entry=arrx[i]
            entry1=entry.reshape(785,1)
            predout[i]=sigmoid(matmul(theta,entry1))
    return(theta,predout)
training()

In [ ]:
def cost():
    pred_out=np.zeros((19999),dtype=float)
    for i in range(0,19999):
        entry=arrx[i]
        entry1=entry.reshape(785,1)
        pred_out[i]=sigmoid(matmul(theta,entry1))
    for k in range(0,19999):
        j=((pred_out[k]-arry[k])*(pred_out[k]-arry[k]))/(2*19999)
    return(j,pred_out)

In [ ]:
test_df

In [ ]:
df_new1 = test_df.rename(columns={'7': 'Label'})

In [ ]:
df_new1['Label'] = df_new1['Label'].replace([0,1,2,3,4,5,6,7,8,9],[1,0,0,0,0,0,0,0,0,0])

In [ ]:
inpx=df_new.drop(["Label"], axis=1)

In [ ]:
list2=[]
for i in range (0,9999):
    list2.append(1)

In [ ]:
inpx.insert(loc=0, column='A', value=list2)

In [ ]:
inparr = inpx.to_numpy()

In [ ]:
pred_Out1=np.zeros((9999),dtype=int)
for i in range(0,9999):
    entry=arrx[i]
    entry1=entry.reshape(785,1)
    pred_Out1[i]=sigmoid(matmul(theta,entry1))

In [ ]:
maty1=df_new1["Label"]
arry1=maty.to_numpy()

In [ ]:
l=int(input("Enter the row for which you want output"))

In [ ]:
print("The probability that output is 0 is {}".format(pred_Out1[l]))