In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import random

In [2]:
train_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_train_small.csv")
test_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_test.csv")


In [3]:
train_df.head()

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [4]:
df_new = train_df.rename(columns={'6': 'Label'})

In [5]:
df_new.head()

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

df_new['Label']= df_new["Label"].replace({1:0, 2: 0, 3: 0, 4: 0, 5 : 0, 6: 0, 7: 0, 8: 0, 9: 0, 0: 1}, inplace=True)

In [6]:
df_new['Label'] = df_new['Label'].replace([0,1,2,3,4,5,6,7,8,9],[1,0,0,0,0,0,0,0,0,0])

In [7]:
df_new

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  \
0          0  0    0    0    0    0    0    0    0    0  ...      0      0   
1          0  0    0    0    0    0    0    0    0    0  ...      0      0   
2          0  0    0    0    0    0    0    0    0    0  ...      0      0   
3          0  0    0    0    0    0    0    0    0    0  ...      0      0   
4          0  0    0    0    0    0    0    0    0    0  ...      0      0   
...      ... ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
19994      1  0    0    0    0    0    0    0    0    0  ...      0      0   
19995      0  0    0    0    0    0    0    0    0    0  ...      0      0   
19996      0  0    0    0    0    0    0    0    0    0  ...      0      0   
19997      0  0    0    0    0    0    0    0    0    0  ...      0      0   
19998      0  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.583  0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [8]:
def sigmoid(z):
    return (1.0 / (1 + np.exp(-z)))

In [9]:
matx=df_new.drop(["Label"], axis=1)

In [10]:
matx

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.581  0.582  \
0      0    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      0    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      0    0    0    0    0    0    0    0    0    0  ...      0      0   
...   ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
19994  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19995  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19996  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19997  0    0    0    0    0    0    0    0    0    0  ...      0      0   
19998  0    0    0    0    0    0    0    0    0    0  ...      0      0   

       0.583  0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0      0  

[19999 rows x 784 columns]

In [11]:
list1=[]
for i in range (0,19999):
    list1.append(1)

In [12]:
matx.insert(loc=0, column='A', value=list1)

In [13]:
matx

A  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
19994  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19996  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19997  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19998  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

       0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [14]:
arrx = matx.to_numpy()
arrx = arrx.astype('float64') 

In [15]:
arrx

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [16]:
maty=df_new["Label"]
arry=maty.to_numpy()
arry = arry.astype('float64') 

In [17]:
arry

array([0., 0., 0., ..., 0., 0., 0.])

In [18]:
theta=np.zeros((1,785),dtype=float)

In [19]:
for i in range(0,785):
    theta[0][i]=0

In [20]:
theta

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [21]:
def matmul(a,b):
    p = len(a)    #rows
    #q = len(a[0]) #columns
    #r = len(b)    
    s = len(b[0])
    #d=np.zeros((3,4),dtype=int)
    d=np.zeros((p,s),dtype=float)
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                d[i][j] += a[i][k] * b[k][j]
    return(d[0][0])


In [22]:
predout=np.zeros((19999),dtype=float)
for i in range(0,19999):
    entry=arrx[i]
    entry1=entry.reshape(785,1)
    predout[i]=sigmoid(matmul(theta,entry1))
    

In [23]:
def ffff(e):
    for i in range(0,19999):
        x=np.sum((predout[i]-arry[i])*arrx[i][e])
    return(x)

In [24]:
def training():
    f=0.0001
    for m in range(0,10):
        for j in range(0,785):
            theta[0][j]=theta[0][j]-((f/19999)*(ffff(j)))
        predout=np.zeros((19999),dtype=float)
        for i in range(0,19999):
            entry=arrx[i]
            entry1=entry.reshape(785,1)
            predout[i]=sigmoid(matmul(theta,entry1))
    return(theta,predout)
training()

(array([[-2.50012501e-08,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+0

In [25]:
def cost():
    pred_out=np.zeros((19999),dtype=float)
    for i in range(0,19999):
        entry=arrx[i]
        entry1=entry.reshape(785,1)
        pred_out[i]=sigmoid(matmul(theta,entry1))
    for k in range(0,19999):
        j=((pred_out[k]-arry[k])*(pred_out[k]-arry[k]))/(2*19999)
    return(j,pred_out)

In [26]:
cost()

(5.135638602278803e-06,
 array([0.48325598, 0.48859944, 0.48112215, ..., 0.48988091, 0.48917065,
        0.45322762]))

Testing

In [27]:
test_df

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [28]:
df_new1 = test_df.rename(columns={'7': 'Label'})

In [29]:
df_new1['Label'] = df_new1['Label'].replace([0,1,2,3,4,5,6,7,8,9],[1,0,0,0,0,0,0,0,0,0])

In [37]:
df_new1

Label  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  \
0         0  0    0    0    0    0    0    0    0    0  ...      0      0   
1         0  0    0    0    0    0    0    0    0    0  ...      0      0   
2         1  0    0    0    0    0    0    0    0    0  ...      0      0   
3         0  0    0    0    0    0    0    0    0    0  ...      0      0   
4         0  0    0    0    0    0    0    0    0    0  ...      0      0   
...     ... ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
9994      0  0    0    0    0    0    0    0    0    0  ...      0      0   
9995      0  0    0    0    0    0    0    0    0    0  ...      0      0   
9996      0  0    0    0    0    0    0    0    0    0  ...      0      0   
9997      0  0    0    0    0    0    0    0    0    0  ...      0      0   
9998      0  0    0    0    0    0    0    0    0    0  ...      0      0   

      0.660  0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [30]:
inpx=df_new1.drop(["Label"], axis=1)

In [31]:
list2=[]
for i in range (0,9999):
    list2.append(1)

In [32]:
inpx.insert(loc=0, column='A', value=list2)

In [53]:
inpx

A  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [33]:
inparr = inpx.to_numpy()

In [48]:
inparr

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [54]:
pred_Out1=np.zeros((9999),dtype=float)
for i in range(0,9999):
    entry=inparr[i]
    entry1=entry.reshape(785,1)
    pred_Out1[i]=sigmoid(matmul(theta,entry1))

In [56]:
maty1=df_new1["Label"]
arry1=maty1.to_numpy()

In [57]:
arry1

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [62]:
l=int(input("Enter the row for which you want output"))

Enter the row for which you want output 3000


In [63]:
print("The probability that output is 0 is {}".format(pred_Out1[l]))

The probability that output is 0 is 0.48903163015333384


THANK YOU
