In [23]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import random
from sklearn import preprocessing
from pandas import DataFrame

In [24]:
train_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_train_small.csv")

Standardisation = preprocessing.StandardScaler()

In [25]:
def sigmoid(z):
    return (1.0 / (1 + np.exp(-z)))

In [26]:
def tanh(z):
    t=(np.exp(z)-np.exp(-z))/(np.exp(z)+np.exp(-z))
    return t

In [27]:
def dtanh(z):
    t=(np.exp(z)-np.exp(-z))/(np.exp(z)+np.exp(-z))
    dt=1-t**2
    return dt

In [28]:
def relu(z):
    return np.maximum(z, 0)

In [29]:
def derir(z):
    z[z<0] = 0
    z[z>=0] = 1
    return z


In [30]:
num_col=train_df.shape[1]-1

In [31]:
num_row=train_df.shape[0]

In [32]:
x_train=train_df.drop(["6"],axis=1)

In [33]:
x_train=x_train.to_numpy()

x_train=Standardisation.fit_transform(x_train)

In [34]:
x_train=x_train.reshape((num_col,num_row))

In [35]:
x_train.shape

(784, 19999)

In [36]:
y_train=train_df["6"]

In [37]:
y_train=y_train.to_numpy()

In [38]:
y_train=y_train.reshape(1,num_row)

In [39]:
y_train.shape

(1, 19999)

In [40]:
y_train

array([[5, 7, 9, ..., 2, 9, 5]], dtype=int64)

In [41]:
y_com=np.zeros((10,num_row))

In [42]:
for i in range(0,num_row):
    o=y_train[0][i]
    y_com[o][i]=1

In [43]:
class neural_network:
    def __init__(self,x_train,y_com,no_of_iters,learn_rate,a,b):
        self.x_train=x_train
        self.y_com=y_com
        #self.change=number
        self.numrain=no_of_iters
        self.rate=learn_rate
        self.num_row=a
        self.num_col=b
    def training(self):
        w1=(np.random.randn(4,self.num_col))*0.01
        w2=(np.random.randn(4,4))*0.01
        w3=(np.random.randn(10,4))*0.01
        b1=np.random.randn(4,1)
        b2=np.random.randn(4,1)
        b3=np.random.randn(10,1)
        
        
        for i in range(0,self.numrain):
            w3t=np.transpose(w3)
            w2t=np.transpose(w2)
            
            z1=(np.dot(w1,self.x_train))+b1
            a1=relu(z1)
            a1t=np.transpose(a1)
         
            
            z2=(np.dot(w2,a1))+b2
            a2=relu(z2)
            a2t=np.transpose(a2)   
            
            z3=(np.dot(w3,a2))+b3
            a3=sigmoid(z3)
            
            dz3=(a3-y_com)
            dw3=(np.dot(dz3,a2t))/self.num_row
            db3=(np.sum(dz3,axis=1,keepdims=True))/self.num_row
            
            dz2=(np.dot(w3t,dz3))*(derir(z2))
            dw2=(np.dot(dz2,a1t))/self.num_row
            db2=(np.sum(dz2,axis=1,keepdims=True))/self.num_row
            
            dz1=(np.dot(w2t,dz2))*(derir(z1))
            dw1=(np.dot(dz1,np.transpose(self.x_train)))/self.num_row
            db1=(np.sum(dz1,axis=1,keepdims=True))/self.num_row
            
            w3=w3-(self.rate*(dw3))
            b3=b3-(self.rate*(db3))
            w2=w2-(self.rate*(dw2))
            b2=b2-(self.rate*(db2))
            w1=w1-(self.rate*(dw1))
            b1=b1-(self.rate*(db1))
            cost=(1/2*self.num_row)*np.sum(np.square(a3-y_com))
            plt.scatter(i,cost,c="red")
        w=[w1,w2,w3]
        b=[b1,b2,b3]
        return w,b
            
            
            
            

In [ ]:
w=neural_network(x_train,y_train,1000,0.00008,num_row,num_col).training()

In [95]:
w1=w[0][0]

In [96]:
w2=w[0][1]

In [97]:
w3=w[0][2]

In [98]:
b1=w[1][0]

In [99]:
b2=w[1][1]

In [100]:
b3=w[1][2]

In [101]:
test_df = pd.read_csv("C:/Users/Dell/Dropbox (Old)/My PC (DESKTOP-9I2HO18)/Downloads/mnist_test.csv")

In [102]:
num_col1=test_df.shape[1]-1

In [103]:
num_row1=test_df.shape[0]

In [104]:
feat1=test_df.drop(["7"],axis=1) 

In [105]:
x_test=feat1.to_numpy()

x_test=Standardisation.fit_transform(x_test)

In [106]:
x_test=x_test.reshape(784,9999)

In [107]:
ydata1=test_df["7"]

In [108]:
y_test=ydata1.to_numpy()
y_test=y_test.astype('int') 

In [109]:
y_test=y_test.reshape(1,num_row1)

In [110]:
def predict():
            
    z1=(np.dot(w1,x_test))+b1
    a1=relu(z1)
    a1t=np.transpose(a1)
         
    z2=(np.dot(w2,a1))+b2
    a2=relu(z2)
    a2t=np.transpose(a2)   
            
    z3=(np.dot(w3,a2))+b3
    a3=sigmoid(z3)
    
    return a3
            
    

In [111]:
a3=predict()
a3             

array([[0.05861998, 0.05017808, 0.01996063, ..., 0.05585839, 0.05452927,
        0.02610886],
       [0.05760355, 0.04725196, 0.01568808, ..., 0.05730352, 0.05462042,
        0.02258492],
       [0.09314661, 0.08783726, 0.06519239, ..., 0.09504786, 0.09291191,
        0.07324321],
       ...,
       [0.07373464, 0.0684027 , 0.04029392, ..., 0.0658957 , 0.06827716,
        0.04364682],
       [0.03531584, 0.02849671, 0.0096138 , ..., 0.03668033, 0.03522342,
        0.014145  ],
       [0.07322012, 0.06459331, 0.032356  , ..., 0.07391249, 0.07092059,
        0.04117299]])

In [112]:
y_ans=a3.argmax(axis=0)
y_ans=y_ans.reshape(1,num_row1)


In [113]:
y_ans

array([[2, 2, 2, ..., 2, 2, 2]], dtype=int64)